version: "2"
services:
  changepassword:
    image: changepassword:t1
    container_name: app
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
        - "7134:7134"
    command: mvn spring-boot:run

#  api-tests:
#      image: changepassword:t1
#      container_name: api-tests
#      depends_on:
#            - "changepassword"
#      command: >
#                        /bin/bash -c "
#                          while(curl -i -H "Accept: application/json" -H "Content-Type: application/json" -o /dev/null -s -w "%{http_code}\n"  -X GET http://localhost:7134/changepassword !=200)
#                          do
#                            echo sleeping;
#                            sleep 1;
#                          done;
#                          echo Connected!;
#                        "
#      command: mvn test -Papi-tests
