version: "2"
services:
  changepassword:
    image: changepassword:t1
    container_name: app
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
        - "9999:9999"
    command: mvn spring-boot:run

  api-tests:
      image: changepassword:t1
      container_name: api-tests
      depends_on:
            - "changepassword"
      command: mvn test -Papi-tests