version: 2
jobs:
  build:
      docker:
        - image: docker:t1
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Start container and verify it is working
            command: docker-compose up -d