version: 2
jobs:
  build:
      machine: true
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Start container and verify it is working
            command: docker-compose up -d